name: accordion
description: A stylish and smooth Accordion list where each item can be expanded or collapsed simply by clicking on the header.
version: 2.6.0
publish_to: none
homepage: https://www.vulcansoft.com
repository: https://github.com/GotJimmy/accordion

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  get:
    git: https://github.com/kumsumit/get.git

dev_dependencies:
  flutter_lints:
    git: https://github.com/kumsumit/flutter_lints.git

flutter:
  uses-material-design: true

topics:
  - lists
  - sections
  - expandable
  - ui

screenshots:
  - description: 'Accordion example in action'
    path: example/accordion_demo.gif
  